export const MyJobs = {
  firstJob: {
    image_url: "/grids_logo_white.jpg",
    job_title: "Startup CEO",
    company_name: "Grids: Buy Now Pay Later",
    job_description: "- Pitch Deck",
    duration: "Mar 2021 - Oct 2021",
    year: 2021,
  },
  secondJob: {
    image_url: "/grids_logo_white.jpg",
    job_title: "Startup CEO",
    company_name: "Grids: Short form News",
    job_description: "- Pitch Deck",
    duration: "Nov 2021 - Mar 2022",
    year: 2022,
  },
  thirdJob: {
    image_url: "/cns_logo.png",
    job_title: "Software Developer",
    company_name: "LG CNS: Intern",
    job_description: "- Mobile Service Development team",
    duration: "Jun 2023 - Aug 2023",
    year: 2023,
  },
  fourthJob: {
    image_url: "/bondit_logo.png",
    job_title: "Software Developer",
    company_name: "Bondit: Frontend Developer",
    job_description: "-Building Landing Page",
    duration: "Aug 2023 - Dec 2023",
    year: 2023,
  },
  fifthJob: {
    image_url: "/factblock_logo.jpg",
    job_title: "Software Developer",
    company_name: "FACTBLOCK: Frontend Developer",
    job_description: "-Fablo App",
    duration: "Feb 2024 - current",
    year: 2024,
  },
};
