export const MyJobs = {
  firstJob: {
    image_url: "/grids_logo_white.jpg",
    job_title: "Startup CEO",
    company_name: "Grids",
    job_description: "Buy Now Pay Later",
    chip: ["Start up", "First Job"],
    duration: "7 Months",
    year: 2021,
  },
  secondJob: {
    image_url: "/grids_logo_white.jpg",
    job_title: "Startup CEO",
    company_name: "Grids",
    chip: ["Start Up", "MVP launch"],
    job_description: "Short Form News Platform",
    duration: "5 Months",
    year: 2022,
  },
  thirdJob: {
    image_url: "/cns_logo.png",
    job_title: "Software Developer",
    chip: ["Intern", "Next.js"],
    company_name: "LG CNS: Intern",
    job_description: "Mobile Service Development team",
    duration: "3 Months",
    year: 2023,
  },
  fourthJob: {
    image_url: "/bondit_logo.png",
    job_title: "Software Developer",
    company_name: "Bondit",
    chip: ["Full-Time", "Flutter, React"],
    job_description: "College Community Calendar",
    duration: "4 Months",
    year: 2023,
  },
  fifthJob: {
    image_url: "/factblock_logo.jpg",
    job_title: "Software Developer",
    company_name: "FACTBLOCK",
    chip: ["Full-Time", "Next.js", "Blockchain"],
    job_description: "Fablo App",
    duration: "Feb 2024 - current",
    year: 2024,
  },
};
